baseurl = "https://zhuokunliu.github.io/"
relativeURLs = true
title = "Zhuokun Liu"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. Candidate in Economics, Goethe University Frankfurt"
    logo = "Portrait.jpg"
    
    
